apiVersion: apps/v1
kind: Deployment
metadata:
  name: agrisense-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: agrisense-server
  template:
    metadata:
      labels:
        app: agrisense-server
    spec:
      containers:
        - name: agrisense-server
          image: agrisense-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"